apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/deploy/crd.yaml
- base/deploy/cw-rbac.yaml
- base/deploy/cw-operator.yaml
- base/deploy/secrets.yaml
- base/deploy/cr.yaml
- base/deploy/ssl-secrets.yaml
- base/deploy/vault-secret.yaml
- resources/backup-s3.yaml
- resources/s3-finalizer.yaml

patchesStrategicMerge:
- overlays/patch-rbac.yaml
- overlays/patch-operator.yaml
- overlays/patch-cr.yaml

namespace: a
commonAnnotations:
  krane.shopify.io/instance-rollout-conditions: '{"success_conditions": [{ "path": "$.status.state", "value": "ready" }], "failure_conditions": [{ "path": "$.status.state", "value": "error" }]}'