apiVersion: pxc.percona.com/v1-10-0
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
spec:
  pxc:
    image: percona/percona-xtradb-cluster:8.0.23-14.1
    affinity:
      antiAffinityTopologyKey:
  haproxy:
    image: docker.io/percona/percona-xtradb-cluster-operator:1.10.0-haproxy
    affinity:
      antiAffinityTopologyKey:
  proxysql:
    image: docker.io/percona/percona-xtradb-cluster-operator:1.10.0-proxysql
  pmm:
    image: docker.io/percona/pmm-client:2.23.0
  backup:
    image: docker.io/percona/percona-xtradb-cluster-operator:1.10.0-pxc8.0-backup
    storages:
      s3-us-west:
        type: s3
        s3:
          bucket: your-bucket-name
          credentialsSecret: aws-credentials-secret
          region: us-west-2
      fs-pvc:
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: s3-us-west